name: Grapevine at Tejon Ranch
favicon: null
layout_spectrum: 0.99516
typography_spectrum: 0.73928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#506647'
    - '#150701'
    - '#90a02f'
    - '#c42e45'
  brandStrength: 0.5
  lightness: 0.6046936009079218
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
