name: Grapevine at Tejon Ranch
favicon: null
layout_spectrum: 0.757942071184516
typography_spectrum: 0.9280755706131458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8356802344787866
  lightness: 0.6046936009079218
  saturation: 0.7434625388123095
  rhythmicContrast: 0.3031713378150016
purpose: []
