name: Grapevine at Tejon Ranch
favicon: null
layout_spectrum: 0.99516
typography_spectrum: 0.73928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#845241'
    - '#2b3e60'
    - '#b6b6b6'
    - '#f4e04b'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
